# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distributed/proto/controlmessages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'distributed/proto/controlmessages.proto\x12\x0f\x63ontrolmessages\"{\n\nDeviceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x12\n\nprocessors\x18\x03 \x01(\x05\x12\x0e\n\x06memory\x18\x04 \x03(\x04\x12\x12\n\nip_address\x18\x05 \x01(\t\x12\x19\n\x11\x61gent_port_offset\x18\x06 \x01(\x05\"\xa2\x01\n\nSystemInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nexperiment\x18\x02 \x01(\t\x12\x17\n\x0f\x63trl_ip_address\x18\x03 \x01(\t\x12\x19\n\x11\x62\x61ndwidth_setting\x18\x04 \x01(\x05\x12>\n\x12offloading_targets\x18\x05 \x03(\x0b\x32\".controlmessages.DownStreamElement\"g\n\x11\x44ownStreamElement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\roffloading_ip\x18\x02 \x01(\t\x12\x17\n\x0foffloading_port\x18\x03 \x01(\x05\x12\x14\n\x0c\x62\x61ndwidth_id\x18\x04 \x01(\x05\"\xab\x01\n\x0f\x43ontainerConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndocker_tag\x18\x02 \x01(\t\x12\x13\n\x0bjson_config\x18\x03 \x01(\t\x12\x12\n\nexecutable\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x05 \x01(\x05\x12\x14\n\x0c\x63ontrol_port\x18\x06 \x01(\x05\x12\x12\n\nmodel_type\x18\x07 \x01(\x05\x12\x13\n\x0binput_shape\x18\x08 \x03(\x05\"/\n\x0f\x43ontainerSignal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x66orced\x18\x02 \x01(\x08\"3\n\x0bPackagedMsg\x12\x13\n\x0btarget_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c*B\n\x10SystemDeviceType\x12\x12\n\x0eUNKNOWN_DEVICE\x10\x00\x12\x0b\n\x07OrinAGX\x10\x03\x12\r\n\tAGXXavier\x10\x06\x62\x06proto3')

_SYSTEMDEVICETYPE = DESCRIPTOR.enum_types_by_name['SystemDeviceType']
SystemDeviceType = enum_type_wrapper.EnumTypeWrapper(_SYSTEMDEVICETYPE)
UNKNOWN_DEVICE = 0
OrinAGX = 3
AGXXavier = 6


_DEVICEINFO = DESCRIPTOR.message_types_by_name['DeviceInfo']
_SYSTEMINFO = DESCRIPTOR.message_types_by_name['SystemInfo']
_DOWNSTREAMELEMENT = DESCRIPTOR.message_types_by_name['DownStreamElement']
_CONTAINERCONFIG = DESCRIPTOR.message_types_by_name['ContainerConfig']
_CONTAINERSIGNAL = DESCRIPTOR.message_types_by_name['ContainerSignal']
_PACKAGEDMSG = DESCRIPTOR.message_types_by_name['PackagedMsg']
DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFO,
  '__module__' : 'distributed.proto.controlmessages_pb2'
  # @@protoc_insertion_point(class_scope:controlmessages.DeviceInfo)
  })
_sym_db.RegisterMessage(DeviceInfo)

SystemInfo = _reflection.GeneratedProtocolMessageType('SystemInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMINFO,
  '__module__' : 'distributed.proto.controlmessages_pb2'
  # @@protoc_insertion_point(class_scope:controlmessages.SystemInfo)
  })
_sym_db.RegisterMessage(SystemInfo)

DownStreamElement = _reflection.GeneratedProtocolMessageType('DownStreamElement', (_message.Message,), {
  'DESCRIPTOR' : _DOWNSTREAMELEMENT,
  '__module__' : 'distributed.proto.controlmessages_pb2'
  # @@protoc_insertion_point(class_scope:controlmessages.DownStreamElement)
  })
_sym_db.RegisterMessage(DownStreamElement)

ContainerConfig = _reflection.GeneratedProtocolMessageType('ContainerConfig', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERCONFIG,
  '__module__' : 'distributed.proto.controlmessages_pb2'
  # @@protoc_insertion_point(class_scope:controlmessages.ContainerConfig)
  })
_sym_db.RegisterMessage(ContainerConfig)

ContainerSignal = _reflection.GeneratedProtocolMessageType('ContainerSignal', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERSIGNAL,
  '__module__' : 'distributed.proto.controlmessages_pb2'
  # @@protoc_insertion_point(class_scope:controlmessages.ContainerSignal)
  })
_sym_db.RegisterMessage(ContainerSignal)

PackagedMsg = _reflection.GeneratedProtocolMessageType('PackagedMsg', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGEDMSG,
  '__module__' : 'distributed.proto.controlmessages_pb2'
  # @@protoc_insertion_point(class_scope:controlmessages.PackagedMsg)
  })
_sym_db.RegisterMessage(PackagedMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SYSTEMDEVICETYPE._serialized_start=731
  _SYSTEMDEVICETYPE._serialized_end=797
  _DEVICEINFO._serialized_start=60
  _DEVICEINFO._serialized_end=183
  _SYSTEMINFO._serialized_start=186
  _SYSTEMINFO._serialized_end=348
  _DOWNSTREAMELEMENT._serialized_start=350
  _DOWNSTREAMELEMENT._serialized_end=453
  _CONTAINERCONFIG._serialized_start=456
  _CONTAINERCONFIG._serialized_end=627
  _CONTAINERSIGNAL._serialized_start=629
  _CONTAINERSIGNAL._serialized_end=676
  _PACKAGEDMSG._serialized_start=678
  _PACKAGEDMSG._serialized_end=729
# @@protoc_insertion_point(module_scope)
